apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-api
  name: web-api-svc
spec:
  ports:
  - name: app-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-api
  type: LoadBalancer
status:
  loadBalancer: {}
